version: '3'

networks:
  saas-template-network:

services:
  grizzly-jersey:
    build:
      context: ./services/grizzly-jersey
      args:
        - SERVICES_GJ_ARTIFACT
        - SERVICES_GJ_HOST
        - SERVICES_GJ_LSTN
        - SERVICES_GJ_PORT
    image: ${COMPOSE_PROJECT_NAME}-grizzly-jersey
    networks:
      - saas-template-network
    ports:
      - $SERVICES_GJ_PORT:$SERVICES_GJ_PORT
  angular:
    build:
      context: ./static/angular
      args:
        - STATIC_ANGULAR_HOST
        - STATIC_ANGULAR_PORT
    image: ${COMPOSE_PROJECT_NAME}-angular
    networks:
      - saas-template-network
    ports:
      - $STATIC_ANGULAR_PORT:80
